name: Add assets to release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build packages
    uses: ./.github/workflows/add-assets-workflow-call.yml
    with:
      upload_url: ${{ github.event.release.upload_url }}
